[package]
name = "tools"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.63", default-features = false }
clap = { version = "3.2.20", features = ["derive"] }
difference = { version = "2.0.0", default-features = false }
ts-bindgen = { version = "0.5.0", default-features = false }
